/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MedicosRouteImport } from './routes/medicos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KitIndexRouteImport } from './routes/kit/index'
import { Route as KitObrigadoRouteImport } from './routes/kit/obrigado'

const MedicosRoute = MedicosRouteImport.update({
  id: '/medicos',
  path: '/medicos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KitIndexRoute = KitIndexRouteImport.update({
  id: '/kit/',
  path: '/kit/',
  getParentRoute: () => rootRouteImport,
} as any)
const KitObrigadoRoute = KitObrigadoRouteImport.update({
  id: '/kit/obrigado',
  path: '/kit/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/medicos': typeof MedicosRoute
  '/kit/obrigado': typeof KitObrigadoRoute
  '/kit/': typeof KitIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/medicos': typeof MedicosRoute
  '/kit/obrigado': typeof KitObrigadoRoute
  '/kit': typeof KitIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/medicos': typeof MedicosRoute
  '/kit/obrigado': typeof KitObrigadoRoute
  '/kit/': typeof KitIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/medicos' | '/kit/obrigado' | '/kit/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/medicos' | '/kit/obrigado' | '/kit'
  id: '__root__' | '/' | '/medicos' | '/kit/obrigado' | '/kit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MedicosRoute: typeof MedicosRoute
  KitObrigadoRoute: typeof KitObrigadoRoute
  KitIndexRoute: typeof KitIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/medicos': {
      id: '/medicos'
      path: '/medicos'
      fullPath: '/medicos'
      preLoaderRoute: typeof MedicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kit/': {
      id: '/kit/'
      path: '/kit'
      fullPath: '/kit/'
      preLoaderRoute: typeof KitIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kit/obrigado': {
      id: '/kit/obrigado'
      path: '/kit/obrigado'
      fullPath: '/kit/obrigado'
      preLoaderRoute: typeof KitObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MedicosRoute: MedicosRoute,
  KitObrigadoRoute: KitObrigadoRoute,
  KitIndexRoute: KitIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
